version: "3.7"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
    ports:
    - "127.0.0.1:2181:2181"

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    links:
    - zookeeper
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
    - "127.0.0.1:9092:9092"
